set nu

"切换标签页 tabnew tabnext tabprev tabclose
nnoremap <c-n> :tabn<cr>
nnoremap <c-p> :tabp<cr>

nnoremap <space> :
"set cuc cul

set nocompatible "不要vim模仿vi模式，建议设置，否则会有很多不兼容的问题
syntax on "打开高亮

set tabstop=4 "让一个tab等于4个空格
set softtabstop=4
set shiftwidth=4 "自动缩进长度
set expandtab "tab转换为空格
set autoindent
set backspace=start,indent,eol "配置删除 相当于set backspace=2

set foldmethod=marker "创建折叠 zf  在括号折叠zf%  关闭折叠zd
set showcmd "show cmd

set t_Co=256
syntax on "语法高亮
set relativenumber "设置相对数字
filetype indent on "不同文件类型执行不同缩进

let mapleader = ";"

nmap <leader>w :w<CR>:q<CR>
nmap <leader>q :q<CR>
"打开一个分屏vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<CR>
"重新读取vimrc
nnoremap <leader>sv :source $MYVIMRC<CR>
inoremap <esc> <nop>
inoremap kj <ESC>

"复制到windows的剪切板
map <F4> : call CopyToWindows()<CR>   
map! <F4> <ESC> : call CopyToWindows()<CR>
func! CopyToWindows()
    exec"w"
    exec "!cat % |/mnt/c/Windows/System32/clip.exe"
endfunc

call plug#begin('~/.vim/plugged')

"Plug 'scrooloose/nerdtree'
"Plug 'Chiel92/vim-autoformat'
"Plug 'ludovicchabant/vim-gutentags'
""Plug 'fatih/vim-go'
""Plug 'scrooloose/syntastic'
"Plug 'skywind3000/vim-auto-popmenu'
"Plug 'skywind3000/vim-dict'

call plug#end()
