set nu
nnoremap <c-n> :tabn<cr>
nnoremap <c-p> :tabp<cr>

nnoremap <space> :
"set cuc cul

set nocompatible "不要vim模仿vi模式，建议设置，否则会有很多不兼容的问题
syntax on"打开高亮
set tabstop=4 "让一个tab等于4个空格
set softtabstop=4
set shiftwidth=4
set autoindent
set backspace=start,indent,eol
set foldmethod=marker
set showcmd
set autoindent
set t_Co=256
syntax on
set relativenumber
filetype indent on
set expandtab

imap <c-a> <esc>ggyGy
let mapleader = ";"
nmap <leader>w :w<CR>:q<CR>
nmap <leader>q :q<CR>
"打开一个分屏vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<CR>
"重新读取vimrc
nnoremap <leader>sv :source $MYVIMRC<CR>

map <F3> :NERDTreeMirror<CR>
map <F3> :NERDTreeToggle<CR>

inoremap <esc> <nop>
inoremap kj <ESC>

map <F4> : call CopyToWindows()<CR> " 复制到windows的剪切板
map! <F4> <ESC> : call CopyToWindows()<CR>
func! CopyToWindows()
    exec"w"
    exec "!cat % |/mnt/c/Windows/System32/clip.exe"
endfunc

call plug#begin('~/.vim/plugged')
Plug 'dense-analysis/ale'
Plug 'ludovicchabant/vim-gutentags'
Plug 'skywind3000/vim-auto-popmenu'
Plug 'skywind3000/vim-dict'
Plug 'skywind3000/vim-preview'
Plug 'skywind3000/gutentags_plus'
call plug#end()


nnoremap <m-u> :PreviewScroll -1<cr>
nnoremap <m-d> :PreviewScroll +1<cr>
inoremap <m-u> <c-\><c-o>:PreviewScroll -1<cr>
inoremap <m-d> <c-\><c-o>:PreviewScroll +1<cr>

source ~/.vim/vimrcs/autotag.vim
source ~/.vim/vimrcs/netrw.vim
source ~/.vim/vimrcs/miniycm.vim
source ~/.vim/vimrcs/ale.vim
"source ~/.vim/vimrcs/gtags.vim



